@base = http://127.0.0.1:8080

POST {{base}}/register

{
    "username":"armin",
    "password":"rostami"
}


###
# @name auth
POST {{base}}/login

{
    "username":"armin",
    "password":"rostami"
}

###
GET {{base}}/validate
Authorization: {{auth.response.headers.Authorization}}


###
DELETE {{base}}/user
Authorization: {{auth.response.headers.Authorization}}
