@base = http://127.0.0.1:8080

POST {{base}}/register

{
    "username":"ali",
    "password":"asdf",
    "email":"aliali@gmail.com",
    "bio":"studying hardware engineering"
}

###
# @name auth
POST {{base}}/login

{
    "username":"armin",
    "password":"asdf"
}

###
GET {{base}}/users
Cookie: {{auth.response.headers.Set-Cookie}}


###
DELETE {{base}}/users
Cookie: {{auth.response.headers.Set-Cookie}}


###
PUT {{base}}/users
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "email":"rostamiarmin@yahoo.com",
    "password":"1234",
    "credit":"10000",
    "_id":"aghsantas"
}

###
POST {{base}}/search

{
    "term":"software"
}