@base = http://127.0.0.1:8000

POST {{base}}/users

{
    "username":"armin2",
    "password":"asdf",
    "email":"rostamiarmin@gmail.com"
}

###
# @name auth
POST {{base}}/login

{
    "username":"armin2",
    "password":"asdf"
}

###
GET {{base}}/users
Cookie: {{auth.response.headers.Set-Cookie}}


###
DELETE {{base}}/users
Cookie: {{auth.response.headers.Set-Cookie}}


###
PUT {{base}}/users
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "email":"rostamiarmin@yahoo.com",
    "password":"1234",
    "credit":"10000"
}



###
# @name addContent
POST {{base}}/contents
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "cid":"dsfs3d4s7d8sdsa2safasadsf5a6",
    "description":"James Bond descends into mystery as he tries to stop a mysterious organisation from eliminating a country's most valuable resource. James Bond descends into mystery as he tries to stop a mysterious organisation from eliminating a country's most valuable resource.",
    "name":"Quantum of Solace (2008) 720p",
    "extension":"mp4",
    "size":1048.69,
    "file_type":"video"
}

###
GET {{base}}/contents?id={{addContent.response.body.id}}
Cookie: {{auth.response.headers.Set-Cookie}}


###
DELETE {{base}}/contents
Cookie: {{auth.response.headers.Set-Cookie}}

{
        "id":"{{addContent.response.body.id}}"
}

###
PUT {{base}}/contents
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "id":"{{addContent.response.body.id}}",
    "name":"casino royal",
    "description":"james bonds' movie",
    "size":3000
}

###
POST {{base}}/search

{
    "description":"bond",
    "extension":"mp4"
}

###
POST {{base}}/contents/rate
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "rating":3.7,
    "content_id":"{{addContent.response.body.id}}"
}