version: "3.4"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DOCKER_ENABLED=1
      - DEBUG=1
    ports:
      - 8000:8000
    restart: on-failure
    depends_on: ["pgsql", "datastore"]

  pgsql:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8001:8001
    depends_on: ["pgsql"]

  datastore:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
